### ISSUE TITLE
нет квеста

### ISSUE THREAD

**Issue by GuardRosgard** [admadm123/TurboWoW-Dragonflight-10.2#109]
![Снимок экрана (178)](https://github.com/admadm123/TurboWoW-Dragonflight-10.2/assets/150108315/c33fa62f-e206-4121-885f-eed6e4d1386b)
https://www.wowhead.com/ru/quest=72712/

**Comment by admadm123** [comment]
> ![Снимок экрана (178)](https://user-images.githubusercontent.com/150108315/280927812-c33fa62f-e206-4121-885f-eed6e4d1386b.png) https://www.wowhead.com/ru/quest=72712/

![image](https://github.com/admadm123/TurboWoW-Dragonflight-10.2/assets/63059326/67859d3f-c2c9-48a1-bb80-28d8546be183)
пользуйтесь аддоном как на экране чтобы сделать скрин и отследить цепочку
