### ISSUE TITLE
3.3.5

### ISSUE THREAD

**Issue by Dedbabaika** [admadm123/TurboWoW-Dragonflight-10.2#110]
![WoWScrnShot_111223_173848](https://github.com/admadm123/TurboWoW-Dragonflight-10.2/assets/148622850/2184742a-7728-4bd1-bb94-65748dacc314)
После того как выкинуло с сервера был в монастыре Библиотека.как зашел в мир Забагалось пати,я не выйти с него не могу не встать в поск подьземелья. Глаз есть а взаимодействовать с ним не могу.и через иконку персонажа тоже нет возможности выйти с пати.[
![WoWScrnShot_111223_172944](https://github.com/admadm123/TurboWoW-Dragonflight-10.2/assets/148622850/399b6bc3-25e9-47d1-a916-44ac886c7a34)
![WoWScrnShot_111223_172958](https://github.com/admadm123/TurboWoW-Dragonflight-10.2/assets/148622850/f82ce28b-20cd-4cf6-8461-a622ac2a8516)
](url)

**Comment by Dedbabaika** [comment]
![Uploading WoWScrnShot_111223_173848.jpg…]()

**Comment by Dedbabaika** [comment]
/

**Comment by admadm123** [comment]
в чате фиолетовым цветом написано что нужно делать
